name: MinigamesLibBungee
main: com.instancedev.minigamesapibungee.Main
version: ${minigames.releaseversion}-${minigames.timestamp}
author: [TheMrQuake,InstanceLabs,mepeisen]
commands:
   mg:
      description: Main command
      usage: /mg [action]
      aliases: [mglib, mgapi, mapi, mglibbungee, join]